include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  transcode-jobs {
    defaultVisibilityTimeout = 10 minutes
    delay = 0 seconds
    receiveMessageWait = 5 seconds
    deadLettersQueue {
      name = "transcode-jobs-dlq"
      maxReceiveCount = 3
    }
  }
  transcode-jobs-dlq { }

  post-events {
    defaultVisibilityTimeout = 2 minutes
    delay = 0 seconds
    receiveMessageWait = 5 seconds
    deadLettersQueue {
      name = "post-events-dlq"
      maxReceiveCount = 3
    }
  }
  post-events-dlq { }
}
